# Name of your application. Used to uniquely configure containers.
service: ai-playground-d1cloud-io

# Name of the container image.
image: versacommerce/ai-playground-d1cloud-io

# Deploy to these servers.
servers:
  web:
    - ai-playground-d1cloud-io
  job:
    hosts:
      - ai-playground-d1cloud-io
    cmd: bin/jobs

# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  # server: registry.digitalocean.com / ghcr.io / ...
  username: vcmarvin

  # Always use an access token rather than real password when possible.
  password:
    - KAMAL_REGISTRY_PASSWORD

# Inject ENV variables into containers (secrets come from .env).
# Remember to run `kamal env push` after making changes!
env:
  clear:
    APP_MAX_THREADS: 3
    RACK_ENV: production
    WEB_CONCURRENCY: 1
    REDIS_URL: redis://172.17.0.1:6379/1
  secret:
    - OPEN_AI_API_KEY

builder:
  dockerfile: Dockerfile.production
  remote:
    arch: amd64
    host: ssh://root@builder-d1cloud-io

accessories:
  redis:
    image: redis/redis-stack:latest
    host: ai-playground-d1cloud-io
    port: "6379:6379"
    directories:
      - redis-data:/data
